services:
  daraja:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --url http://daraja:${PORT} --token ${TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - daraja

volumes:
  redis_data: